version: '3.1'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=false
    volumes:
      - ./:/app
      - ./docker/config/app.php.ini:/usr/local/etc/php/conf.d/coverd-overrides.ini
    env_file: .env.docker
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./:/app:ro,cached
      - ./docker/config/app.nginx.conf:/etc/nginx/conf.d/default.conf
